version: '3.8'

name: geo-collector-bot-postgres

services:
  postgres:
    image: postgis/postgis:14-3.2-alpine
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - APP_DB_USER=geo_collector_bot
      - APP_DB_PASS=geo_collector_bot
      - APP_DB_NAME=geo_collector_bot
    ports:
      - '5438:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d

  bot:
    image: geo-collector-bot:latest
    depends_on:
      - postgres
    environment:
      - TELEGRAM_AUTH_TOKEN=${TELEGRAM_AUTH_TOKEN}
      - LOG_LEVEL=trace
    ports:
      - '8080:8080'
    volumes:
      - ./config.json:/home/node/config.json
      - ./media:/home/node/media
